---
- name: Windows Facts report
  hosts: windows

  tasks:
    - name: Register User Name
      ansible.builtin.set_fact:
        windows_user: "{{ ansible_user }}"
      no_log: true
      delegate_to: localhost
      run_once: true

    - name: Register Password
      ansible.builtin.set_fact:
        windows_password: "{{ ansible_password }}"
      no_log: true
      delegate_to: localhost
      run_once: true

    - name: Gather Ansible Facts About Host
      ansible.builtin.setup:
        gather_subset:
          - all
      register: my_ansible_facts
      
    - name: Debugging "my_ansible_facts" variable Fact
      ansible.builtin.debug:
        msg: "{{ my_ansible_facts }}"

    - name: Create JSON-file with Ansible Facts
      copy:
        content: |
          {% for host in ansible_play_hosts %}
          {{ hostvars[host].my_ansible_facts | to_nice_json }}
          {% endfor %}
        dest: ../documentation/servers/WINDOWS/json/server_facts.json
      delegate_to: localhost
      run_once: true

    - name: Create YAML-file with Ansible_fact
      ansible.builtin.copy:
        content: |
          {% for host in ansible_play_hosts %}
          {{ hostvars[host].my_ansible_facts | to_nice_yaml }}
          {% endfor %}
        dest: ../documentation/servers/WINDOWS/yaml/server_facts.yml
      delegate_to: localhost
      run_once: true

    - name: Add Headers row to YAML-file.
      lineinfile:
        path: ../documentation/servers/WINDOWS/yaml/server_facts.yml
        insertbefore: BOF
        line: ---
      delegate_to: localhost

    - name: Set ALL new variables Facts
      ansible.builtin.set_fact:
        nodename: "{{ my_ansible_facts['nodename'] }}"
        domain: "{{ my_ansible_facts['domain'] }}"
        windows_domain_member: "{{ my_ansible_facts['windows_domain_member'] }}"
        windows_domain_role: "{{ my_ansible_facts['windows_domain_role'] }}"
        distribution: "{{ my_ansible_facts['distribution'] }}"
        distribution_major_version: "{{ my_ansible_facts['distribution_major_version'] }}"
        distribution_version: "{{ my_ansible_facts['distribution_version'] }}"
        architecture: "{{ my_ansible_facts['architecture'] }}"
        bios_date: "{{ my_ansible_facts['bios_date'] }}"
        bios_version: "{{ my_ansible_facts['bios_version'] }}"
      #  connection_name: "{{ my_ansible_facts | ['interfaces']['connection_name'] }}"
      # connection_name: "{{ my_ansible_facts | ['interfaces']['interface_name'] }}"
      #
        connection_name: "{{ my_ansible_facts | community.general.json_query('ansible_interfaces[*].connection_name') }}"
      #  interface_name: "{{ my_ansible_facts | community.general.json_query('interfaces[*].interface_name') }}"
        ipv4_address: "{{ my_ansible_facts | community.general.json_query('ip_addresses[0]') }}"
        ipv6_address: "{{ my_ansible_facts | community.general.json_query('ip_addresses[1]') }}"
      #  default_gateway: "{{ my_ansible_facts | community.general.json_query('interfaces[*].default_gateway') }}"
      #  mac_address: "{{ my_ansible_facts | community.general.json_query('interfaces[*].macaddress') }}"
        lastboot: "{{ my_ansible_facts['lastboot'] }}"
        reboot_pending: "{{ my_ansible_facts['reboot_pending'] }}"
        uptime: "{{ my_ansible_facts['uptime_seconds'] }}"
        machine_id: "{{ my_ansible_facts['machine_id'] }}"
        total_memory: "{{ my_ansible_facts['memtotal_mb'] }}"
        processor: "{{ my_ansible_facts | community.general.json_query('processor[1]') }}"
        processor_cores: "{{ my_ansible_facts['processor_cores'] }}"
        processor_count: "{{ my_ansible_facts['processor_count']}}"
        product_name: "{{ my_ansible_facts['product_name'] }}"


- name: Git-Add-Commit-Push
  hosts: student1-ansible-1
  vars:
    git_commit: 'Recording variables'
    git_message: 'Lets see all variables'
  tasks:
    - name: Set git_message
      ansible.builtin.set_fact:
        git_message: "{{ git_commit }}"

    - name: Git-Addition 
      ansible.builtin.shell: git add ../*
      delegate_to: localhost

    - name: Git-commiting
      ansible.builtin.shell: git commit -m "{{ git_message }}"
      delegate_to: localhost

    - name: Git-pushing
      ansible.builtin.shell: git push
      delegate_to: localhost 