---
- name: Windows Facts report
  hosts: windows

  tasks:
    - name: Register User Name
      ansible.builtin.set_fact:
        windows_user: "{{ ansible_user }}"
      no_log: true
      delegate_to: localhost
      run_once: true

    - name: Register Password
      ansible.builtin.set_fact:
        windows_password: "{{ ansible_password }}"
      no_log: true
      delegate_to: localhost
      run_once: true

    - name: Gather Ansible Facts About Host
      ansible.builtin.setup:
        gather_subset:
          - all

    - name: Debugging "ansible_facts" variable Fact
      ansible.builtin.debug:
        msg: "{{ ansible_facts }}"

    - name: Create JSON-file with Ansible Facts
      copy:
        content: |
          {% for host in ansible_play_hosts %}
          {{ hostvars[host].ansible_facts | to_nice_json }}
          {% endfor %}
        dest: ../documentation/servers/WINDOWS/json/server_facts.json
      delegate_to: localhost
      run_once: true

    - name: Create YAML-file with Ansible_fact
      ansible.builtin.copy:
        content: |
          {% for host in ansible_play_hosts %}
          {{ hostvars[host].ansible_facts | to_nice_yaml }}
          {% endfor %}
        dest: ../documentation/servers/WINDOWS/yaml/server_facts.yml
      delegate_to: localhost
      run_once: true

    - name: Add Headers row to YAML-file.
      lineinfile:
        path: ../documentation/servers/WINDOWS/yaml/server_facts.yml
        insertbefore: BOF
        line: ---
      delegate_to: localhost

    - name: Set ALL new variables Facts
      ansible.builtin.set_fact:
        nodename: "{{ ansible_facts.nodename }}"
        domain: "{{ ansible_facts.interfaces[0].dns_domain }}"
        windows_domain_member: "{{ ansible_facts.windows_domain_member }}"
        windows_domain_role: "{{ ansible_facts.windows_domain_role }}"
        distribution: "{{ ansible_facts.distribution }}"
        distribution_major_version: "{{ ansible_facts.distribution_major_version }}"
        distribution_version: "{{ ansible_facts.distribution_version }}"
        architecture: "{{ ansible_facts.architecture }}"
        bios_date: "{{ ansible_facts.bios_date }}"
        bios_version: "{{ ansible_facts.bios_version }}"
        connection_name: "{{ ansible_facts.interfaces[0].connection_name }}"
        interface_name: "{{ ansible_facts.interfaces[0].interface_name }}"
        ipv4_address: "{{ ansible_facts.interfaces[0].ipv4.address }}"
        ipv6_address: "{{ ansible_facts.interfaces[0].ipv6.address }}"
        default_gateway: "{{ ansible_facts.interfaces[0].default_gateway }}"
        mac_address: "{{ ansible_facts.interfaces[0].macaddress }}"
        lastboot: "{{ ansible_facts.lastboot }}"
        reboot_pending: "{{ ansible_facts.reboot_pending }}"
        uptime: "{{ ansible_facts.uptime_seconds }}"
        machine_id: "{{ ansible_facts.machine_id }}"
        total_memory: "{{ ansible_facts.memtotal_mb }}"
        processor: "{{ ansible_facts.env.PROCESSOR_IDENTIFIER }}"
        processor_cores: "{{ ansible_facts.processor_cores }}"
        processor_count: "{{ ansible_facts.processor_count }}"
        product_name: "{{ ansible_facts.product_name }}"

    - name: Print ALL new elements
      ansible.builtin.debug:
            msg: 
              node_name: "{{ nodename }}"
              dns_domain: "{{ domain }}"
              windows_domains_member: "{{ windows_domain_member }}"
              connectiones_name: "{{ connection_name }}"
              enterfaces_name: "{{ interface_name }}"
              ipv4: "{{ ipv4_address }}"
              ipv6: "{{ ipv6_address }}"


#- name: Git-Add-Commit-Push
#  hosts: student1-ansible-1
#  vars:
#    git_commit: 'Recording variables'
#    git_message: 'Lets see all variables'
#  tasks:
#    - name: Set git_message
#      ansible.builtin.set_fact:
#        git_message: "{{ git_commit }}"
#
#    - name: Git-Addition 
#      ansible.builtin.shell: git add ../*
#      delegate_to: localhost

#    - name: Git-commiting
#      ansible.builtin.shell: git commit -m "{{ git_message }}"
#      delegate_to: localhost
#    - name: Git-pushing
#      ansible.builtin.shell: git push
#      delegate_to: localhost 